### ISSUE TITLE
Importing token without Trust Bundle throws an error

### ISSUE THREAD

**Issue by cdmadrigal** [Venafi/terraform-provider-venafi-token#12]
**PROBLEM SUMMARY**
When importing a refresh token, if you do not include the variable "Trust_Bundle", Terraform throws an error.

**STEPS TO REPRODUCE**
terraform import venafi-token_credential.example 'url=<value>,refresh_token=<value>'

**EXPECTED RESULTS**
Token properly imports in to terraform

**ACTUAL RESULTS**
```
│ Error: Client Error
│ 
│ Unable to rotate token, got error: terraform vcert client error: terraform vcert client error: unable to read trust bundle file at []: open : no such file or directory
```

**ENVIRONMENT DETAILS**
Mac OS

**Comment by rvelaVenafi** [comment]
Issue haas been identified. Fix will be available in next release v0.1.1
