### ISSUE TITLE
Allow specifying the scope when using the venafi-token_credential resource with username and password

### ISSUE THREAD

**Issue by brental** [Venafi/terraform-provider-venafi-token#15]
**BUSINESS PROBLEM**
When using the venafi-token_credential resource with a username and password there is no way to specify the scope of the auth token that the resource returns. This means that the username and password option cannot be used to create venafi_policy resources as the access token that is generated does not have the required scope for creating policy resources. Trying to do so results in a insufficient_scope error when terraform tries to created the venafi_policy resource.

**PROPOSED SOLUTION**
Add a scope argument to the venafi-token_credential resource so that when using a username and password with that resource the scope of the generated access token can be specified as well. It could default to whatever scope is currently used to avoid breaking existing consumers of the resource. This would allow specifying a scope of 'certificate:manage,revoke;configuration:manage' which would allow for creating venafi_policy resources as well as venafi_certificate resources.

**CURRENT ALTERNATIVES**
Authenticating using the vedauth API with the scope 'certificate:manage,revoke;configuration:manage' and passing the access token into terraform and using it directly with the provider for the venafi_policy resource.

**VENAFI EXPERIENCE**
I have been using Venafi products for 6 months.

**Comment by brental** [comment]
No response after 3 months. Venafi clearly aren't interested in properly monitoring and responding to GitHub issues so just going to close.

**Comment by cisiu** [comment]
@brental why this ticket is not planned? i also have problem that in my work we cannot have mangae,revoke scope which is default on this provider

**Comment by brental** [comment]
@cisiu I closed the issue due to it becoming obvious from the lack of responses to issues on this and other Venafi repos that they don't really seem interested in addressing issues or developing the repos properly. The only options for closing it were Completed or Not Planned and Not Planned seemed the most accurate due to the lack of any response from the repo maintainers.
